### ISSUE TITLE
missing usb relay instructions

### ISSUE THREAD

**Issue by svfrd** [vic42/Hamapics#1]
hi, i'd like to install to tasmota in this power strip.
The usb relay modifications needs some explanation and instruction.

~~What's the purpose on unsolder the usb relay?~~
EDIT: Unsolder the usb relay to get access to gpio0?

best regards

**Comment by vic42** [comment]
I unsoldered the relay solely to attain easier access to GPIO0 on the rear side of the ESP module.
That's all there is to it.
